# SPDX-License-Identifier: MIT
---

- name: List optional metric collection agents to be enabled
  debug:
    msg: "NeedInstall agent: {{ item }} from {{ pcp_optional_agents }}"
  loop: "{{ pcp_optional_agents|default([]) }}"

- name: Extract metric collection configuration file content
  command: "cat {{ __pcp_pmcd_conf }}"
  register: pmcd_conf
  changed_when: false

- name: Ensure optional metric collection agents are enabled
  file:
    path: "{{ __pcp_agents_path }}/{{ item }}/.NeedInstall"
    mode: u=rw,g=r,o=r
    state: touch
  loop: "{{ pcp_optional_agents|default([]) }}"
  when: pmcd_conf.stdout.find(item) == -1
  register: __metrics_register_changed_coll_agents

- name: Ensure explicit metric label path exists
  file:
    path: "{{ __pcp_explicit_labels_path }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Ensure implicit metric label path exists
  file:
    path: "{{ __pcp_implicit_labels_path }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Ensure any explicit metric labels are configured
  template:
    src: pmcd.explicit.labels.j2
    dest: "{{ __pcp_explicit_labels_path }}/ansible-managed"
    mode: 0644
  register: __metrics_register_changed_explicit

- name: Ensure any implicit metric labels are configured
  template:
    src: pmcd.implicit.labels.j2
    dest: "{{ __pcp_implicit_labels_path }}/ansible-managed"
    mode: 0644
  register: __metrics_register_changed_implicit

- name: Ensure performance metric collector is configured
  template:
    src: pmcd.defaults.j2
    dest: "{{ __pcp_pmcd_defaults_path }}"
    mode: 0644
  register: __metrics_register_changed_coll

- name: Ensure performance metric collector system accounts are configured
  user:
    name: "{{ item.user }}"
    system: yes
  when: item.user is defined
  with_items: "{{ pcp_accounts }}"

- name: Ensure performance metric collector SASL accounts are configured
  shell: |
    set -o pipefail
    sasldblistusers2 -f "{{ __pcp_pmcd_sasldb_path }}" | grep -q "^{{ item.sasluser }}@"
    [ $? -eq 0 ] && exit 0
    echo "Creating new {{ item.sasluser }} user in {{ __pcp_pmcd_sasldb_path }}"
    echo "{{ item.saslpassword }}" | saslpasswd2 -a pmcd "{{ item.sasluser }}"
    chown root:pcp "{{ __pcp_pmcd_sasldb_path }}"
    chmod 640 "{{ __pcp_pmcd_sasldb_path }}"
    exit 0
  register: ensure_sasl_configured
  changed_when: "'Creating new SASL account' in ensure_sasl_configured.stdout"
  when: item.sasluser is defined
  with_items: "{{ pcp_accounts }}"

- name: Ensure performance metric collector authentication is configured
  template:
    src: pmcd.sasl2.conf.j2
    dest: "{{ __pcp_pmcd_saslconf_path }}"
    mode: 0644
  register: __metrics_register_changed_coll_auth
  when: pcp_accounts|d([])

- name: Set variable to do pmcd restart if needed
  set_fact:
    __metrics_restart_pmcd: |
      __metrics_register_changed_coll_agents is changed or
      __metrics_register_changed_explicit is changed or
      __metrics_register_changed_implicit is changed or
      __metrics_register_changed_coll is changed or
      (__metrics_register_changed_coll_auth is defined and
       __metrics_register_changed_coll_auth is changed)

- name: Ensure performance metric collector is running and enabled on boot
  service:
    name: pmcd
    state: started
    enabled: yes
  when: not __metrics_restart_pmcd

- name: Ensure performance metric collector is restarted and enabled on boot
  service:
    name: pmcd
    state: restarted
    enabled: yes
  when: __metrics_restart_pmcd | bool
