# SPDX-License-Identifier: MIT
---

- name: Setup metric collection service
  include_role:
    name: performancecopilot.pcp
  vars:
    pcp_pmlogger_discard: "{{ retention_days }}"
    pcp_target_hosts: "{{ monitored_hosts }}"
    pcp_rest_api: "{{ with_query_service }}"
