# SPDX-License-Identifier: MIT
---

- name: Set platform/version specific variables
  include_vars: "{{ item }}"
  loop:
    - "{{ role_path }}/vars/{{ ansible_os_family }}.yml"
    - "{{ role_path }}/vars/{{ ansible_distribution }}.yml"
    - "{{ role_path }}/vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ role_path }}/vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: item is file

- name: Install Performance Co-Pilot packages
  package:
    name: "{{ __pcp_packages + __pcp_packages_extra + pcp_optional_packages }}"
    state: present

- name: Install authentication packages
  package:
    name: "{{ __pcp_sasl_packages }}"
    state: present
  when:
    - __pcp_sasl_packages | d([])
    - pcp_sasl_accounts | d([])

- include_tasks: pmcd.yml

- include_tasks: pmie.yml

- include_tasks: pmlogger.yml

- include_tasks: pmproxy.yml
  when: pcp_rest_api | bool
