- block:
    - name: Log into logging project
      shell: oc project logging

    - name: Remove metrics index uuid files
      file:
        state: absent
        path: '{{ item }}'
      with_items:
        - /root/metrics-{{ env_name }}-uuid

    - name: Getting the metrics-{{ env_name}} uuid
      shell: oc get project metrics-{{ env_name }} -o jsonpath='{.metadata.uid}' > /tmp/metrics-{{ env_name }}-uuid

    - name: Copy certificates to engine machine
      fetch:
        src: '/tmp/{{ item }}'
        dest: '{{ metrics_pkg_sysconf_dir }}/{{ item }}'
        flat: yes
      with_items:
        - metrics-{{ env_name }}-uuid

    - name: Read metrics index uuid
      delegate_to: localhost
      run_once: true
      set_fact:
        metrics_index_uuid: "{{ lookup('file', metrics_pkg_sysconf_dir+'/metrics-'+env_name+'-uuid') }}"

    - name: Install Viaq metrics store config file
      delegate_to: localhost
      run_once: true
      template:
        src: viaq_post_install_params.conf
        dest: '{{ metrics_config_yml_dir }}/10-viaq_config.yml'
        owner: '{{ metrics_config_yml_d_owner }}'
        group: '{{ metrics_config_yml_d_group }}'
        mode: '{{ metrics_config_yml_d_mode }}'

    - name: Include metrics config.yml.d vars directory
      include_vars:
        dir: '{{ metrics_config_yml_dir }}'
        ignore_files: ['README.md']
      run_once: true

  when: viaq_metrics_store|default(true)|bool and fluentd_output_plugin|default("elasticsearch") == "elasticsearch"
