---
- name: Install collectd package
  yum:
    name: '{{ collectd_package_name }}'
    state: latest
  when: manage_packages|default(true)
  notify: restart collectd

- name: Install collectd plugins
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - '{{ collectd_plugin_packages }}'
  when:
    - manage_packages|default(true)
  notify: restart collectd
