---
- name: Check if metrics config.yml file exist
  stat:
    path: "{{ metrics_config_yml_file }}"
  register: stat_result
  run_once: true
  delegate_to: localhost

- name: Include metrics config.yml file
  include_vars:
    file: '{{ metrics_config_yml_file }}'
  when: stat_result.stat.exists == True
  run_once: true
  delegate_to: localhost

- name: Include metrics config.yml.d vars directory
  include_vars:
    dir: '{{ metrics_config_yml_dir }}'
    ignore_files: ['README.md']
  run_once: true
  delegate_to: localhost
