---
- hosts: analysis
  roles:
    - role: linux-system-roles.metrics
      vars:
        metrics_query_service: true
        metrics_graph_service: true
        metrics_monitored_hosts: ["shard", "slick"]
        metrics_retention_days: 10
