---
- hosts: monitoring
  roles:
    - role: performancecopilot.pcp
      vars:
        pcp_rest_api: true
        pcp_pmlogger_interval: 10
        pcp_pmlogger_discard: 5
        pcp_target_hosts: [slick, shard]
