# yamllint disable rule:line-length
name: Sync ansible-pcp git subtree
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "42 1 * * *"

jobs:
  subtree:
    runs-on: ubuntu-latest
    name: git subtree merge
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: subtree merge
        run: |
          set -euxo pipefail
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git subtree pull --prefix vendor/github.com/performancecopilot/ansible-pcp https://github.com/performancecopilot/ansible-pcp.git HEAD --squash 2>&1 | grep --quiet "Subtree is already at commit"
          [ $? -ne 0 ] && git push
